services:
  - type: web
    name: resume-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r resume-analyzer/requirements.txt
    startCommand: python resume-analyzer/rank-resume.py
    envVars:
      - key: GEMINI_KEY
        sync: false
